// src/embed.vue
<template>
  <div :style="{ display: 'contents' }" ref="wrapper"></div>
</template>

<script>
export default {
  name: "DangerousHTML",
  props: ['html'],
  mounted(){
    if (!this.html || !this.$refs?.wrapper) {
      return
    }
    const slotHtml = document.createRange().createContextualFragment(this.html);
    this.$refs.wrapper.append(slotHtml)
  },
};
</script>

// src/embed.tsx
import React, { useRef, useEffect } from "react";

const DangerousHTML = ({ html }) => {
  const ref = useRef(null);

  useEffect(() => {
    if (!html || !ref.current) {
      return;
    }
    const slotHtml = document.createRange().createContextualFragment(html);
    ref.current.append(slotHtml);
  }, []);

  return <div style={{ display: 'contents' }} ref={ref}></div>;
};

export default DangerousHTML;
